# Generated by Django 6.0.1 on 2026-01-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_order_orderitem_profile_delete_todoitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('restaurant', 'Restaurant'), ('customer', 'Customer')], max_length=20),
        ),
    ]
