# Generated by Django 6.0.2 on 2026-02-27 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0007_profile_extra_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('new_order', 'New Order'), ('order_approved', 'Order Approved'), ('order_rejected', 'Order Rejected'), ('order_out_of_stock', 'Item Out of Stock'), ('order_status_update', 'Order Status Update'), ('order_delivered', 'Order Delivered')], max_length=30),
        ),
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('customer', 'Customer')], max_length=20),
        ),
    ]
